export const styles = {
  container: {
    maxWidth: "750px",
    margin: "2rem auto",
    borderRadius: "12px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
    overflow: "hidden",
    background: "#ffffff",
    display: "flex",
    flexDirection: "column",
    height: "90vh",
  },
  header: {
    background: "#0d6efd",
    padding: "1rem",
    color: "white",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  statusBadge: {
    background: "#fff",
    color: "#0d6efd",
    padding: "3px 10px",
    borderRadius: "8px",
    fontSize: "0.8rem",
    fontWeight: "bold",
  },
  topButtons: {
    display: "flex",
    gap: "10px",
    padding: "0.7rem",
    borderBottom: "1px solid #ddd",
    background: "#f1f1f1",
  },
  smallBtn: {
    padding: "0.5rem 1rem",
    background: "#6c757d",
    color: "white",
    borderRadius: "8px",
    border: "none",
    cursor: "pointer",
  },
  chatBox: {
    flex: 1,
    padding: "1rem",
    background: "#f7f7f9",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
  },
  msgBubble: (role) => ({
    maxWidth: "75%",
    margin: "8px 0",
    padding: "12px 16px",
    borderRadius: "16px",
    alignSelf: role === "user" ? "flex-end" : "flex-start",
    background: role === "user" ? "#0d6efd" : "#e9ecef",
    color: role === "user" ? "white" : "black",
    whiteSpace: "pre-wrap",
    boxShadow: "0 2px 6px rgba(0,0,0,0.1)",
  }),
  timestamp: {
    fontSize: "0.7rem",
    color: "#888",
    marginTop: "4px",
    marginLeft: "4px",
  },
  inputArea: {
    display: "flex",
    padding: "0.8rem",
    borderTop: "1px solid #ddd",
    background: "white",
  },
  input: {
    flex: 1,
    padding: "0.8rem",
    borderRadius: "8px",
    border: "1px solid #ccc",
    fontSize: "1rem",
  },
  sendButton: {
    marginLeft: "10px",
    padding: "0 1.3rem",
    background: "#0d6efd",
    color: "white",
    borderRadius: "8px",
    border: "none",
    cursor: "pointer",
  }
};
